FROM node:20-alpine AS deps
WORKDIR /app

RUN apk add --no-cache ca-certificates \
  && corepack enable \
  && corepack prepare yarn@1.22.22 --activate

COPY package.json yarn.lock ./

# ВАЖНО: yarn v1 использует "resolved" URL из yarn.lock (часто это registry.yarnpkg.com)
# Меняем на registry.npmjs.org, чтобы реально качать оттуда.
RUN sed -i 's#https://registry.yarnpkg.com/#https://registry.npmjs.org/#g' yarn.lock \
  && yarn cache clean --all \
  && yarn install --frozen-lockfile --network-timeout 600000
# -------------------------
# builder
# -------------------------
FROM node:20-alpine AS builder
WORKDIR /app

RUN corepack enable \
  && corepack prepare yarn@1.22.22 --activate

ARG NEXT_PUBLIC_NAME
ARG NEXT_PUBLIC_SITE_LANG
ARG NEXT_PUBLIC_PRERENDER_LIMIT
ARG NEXT_PUBLIC_BASE
ARG NEXT_PUBLIC_INDEX
ARG NEXT_PUBLIC_RATES_MIN
ARG NEXT_PUBLIC_RATES_RENDER_MIN
ARG NEXT_PUBLIC_MIN_RATES_MAP
ARG NEXT_PUBLIC_TELEGRAM_SUPPORT
ARG NEXT_PUBLIC_TELEGRAM_BOT
ARG NEXT_PUBLIC_TELEGRAM_CHAT
ARG NEXT_PUBLIC_GOOGLE_MAPS_KEY
ARG NEXT_PUBLIC_BOT_USERNAME
ARG NEXT_PUBLIC_BOT_START_SECRET
ARG NEXT_PUBLIC_BOT_ALWAYS_VERIFY
ARG NEXT_PUBLIC_TELEGRAM_VERIFY_URL
ARG NEXT_PUBLIC_TELEGRAM_VERIFY_BY_SLUG_URL
ARG NEXT_PUBLIC_ALLOW_CRAWLERS
ARG NEXT_PUBLIC_COINGECKO_URL
ARG SITE_URL
ARG DEBUG_EXCHANGER_MAP
ARG STRAPI_AUTH_IDENTIFIER
ARG STRAPI_AUTH_PASSWORD
ARG USE_INTERNAL
ARG IS_DEV
ARG INTERNAL_CMS_URL
ARG INTERNAL_SERVER_URL
ARG INTERNAL_CONVERTER_URL

ENV NEXT_PUBLIC_NAME=$NEXT_PUBLIC_NAME \
    NEXT_PUBLIC_SITE_LANG=$NEXT_PUBLIC_SITE_LANG \
    NEXT_PUBLIC_PRERENDER_LIMIT=$NEXT_PUBLIC_PRERENDER_LIMIT \
    NEXT_PUBLIC_BASE=$NEXT_PUBLIC_BASE \
    NEXT_PUBLIC_INDEX=$NEXT_PUBLIC_INDEX \
    NEXT_PUBLIC_RATES_MIN=$NEXT_PUBLIC_RATES_MIN \
    NEXT_PUBLIC_RATES_RENDER_MIN=$NEXT_PUBLIC_RATES_RENDER_MIN \
    NEXT_PUBLIC_MIN_RATES_MAP=$NEXT_PUBLIC_MIN_RATES_MAP \
    NEXT_PUBLIC_TELEGRAM_SUPPORT=$NEXT_PUBLIC_TELEGRAM_SUPPORT \
    NEXT_PUBLIC_TELEGRAM_BOT=$NEXT_PUBLIC_TELEGRAM_BOT \
    NEXT_PUBLIC_TELEGRAM_CHAT=$NEXT_PUBLIC_TELEGRAM_CHAT \
    NEXT_PUBLIC_GOOGLE_MAPS_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_KEY \
    NEXT_PUBLIC_BOT_USERNAME=$NEXT_PUBLIC_BOT_USERNAME \
    NEXT_PUBLIC_BOT_START_SECRET=$NEXT_PUBLIC_BOT_START_SECRET \
    NEXT_PUBLIC_BOT_ALWAYS_VERIFY=$NEXT_PUBLIC_BOT_ALWAYS_VERIFY \
    NEXT_PUBLIC_TELEGRAM_VERIFY_URL=$NEXT_PUBLIC_TELEGRAM_VERIFY_URL \
    NEXT_PUBLIC_TELEGRAM_VERIFY_BY_SLUG_URL=$NEXT_PUBLIC_TELEGRAM_VERIFY_BY_SLUG_URL \
    NEXT_PUBLIC_ALLOW_CRAWLERS=$NEXT_PUBLIC_ALLOW_CRAWLERS \
    NEXT_PUBLIC_COINGECKO_URL=$NEXT_PUBLIC_COINGECKO_URL \
    SITE_URL=$SITE_URL \
    DEBUG_EXCHANGER_MAP=$DEBUG_EXCHANGER_MAP \
    STRAPI_AUTH_IDENTIFIER=$STRAPI_AUTH_IDENTIFIER \
    STRAPI_AUTH_PASSWORD=$STRAPI_AUTH_PASSWORD \
    USE_INTERNAL=$USE_INTERNAL \
    IS_DEV=$IS_DEV \
    INTERNAL_CMS_URL=$INTERNAL_CMS_URL \
    INTERNAL_SERVER_URL=$INTERNAL_SERVER_URL \
    INTERNAL_CONVERTER_URL=$INTERNAL_CONVERTER_URL

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NODE_ENV=production
RUN yarn build

# -------------------------
# runner
# -------------------------
FROM node:20-alpine AS runner
WORKDIR /app

RUN corepack enable \
  && corepack prepare yarn@1.22.22 --activate

ENV NODE_ENV=production

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.js ./next.config.js
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000
CMD ["yarn", "start", "-p", "3000"]
