import type { LocaleBundle } from "../types";
const messages: Record<string,string>={
  "Домой":"Startseite","Главная":"Startseite","Главная страница":"Startseite","Проживание":"Unterkunft","Программа":"Programm","Навигация":"Navigation","Университеты":"Universitäten","Истории участников":"Erfahrungsberichte","Услуги":"Leistungen","Как проходит обучение":"So läuft das Programm ab","Консультация":"Beratung","Оставить заявку":"Jetzt anfragen","Летняя школа":"Sommerschule","Политика конфиденциальности":"Datenschutzerklärung","Страницы пока не существует":"Diese Seite gibt es noch nicht","Что входит в программу":"Das ist im Programm enthalten",
  "Подготовка к поступлению в колледжи и университеты США":"Vorbereitung auf die Zulassung an US-Colleges und Universitäten","Курсы в Бостоне, поездка по кампусам университетов лиги плюща":"Kurse in Boston und Besuche auf Ivy-League-Campussen","Программа на 2 недели":"Zweiwöchiges Programm","Почему выбирают нас":"Warum Familien uns wählen","Мы не продаем тур. Мы готовим к поступлению.":"Das ist keine Rundreise. Wir bereiten auf die Bewerbung vor.","Стоимость программы":"Programmpreis","От $3,000 за 2 недели":"Ab 3.000 US-Dollar für zwei Wochen","Финальная стоимость зависит от состава программы":"Der Endpreis hängt vom gewählten Programm ab","Узнать точную стоимость":"Genauen Preis anfragen",
  "Обучение в кампусе Гарварда":"Unterricht auf dem Harvard-Campus","Посещение университетов Бостона, Нью-Хевена и Нью-Йорка":"Besuche an Universitäten in Boston, New Haven und New York","Полное сопровождение, проживание, трансфер и поддержка":"Umfassende Betreuung, Unterkunft, Transfers und Unterstützung","Личное знакомство с сотрудниками университетов и студентами":"Persönliche Treffen mit Universitätsmitarbeitern und Studierenden","Неделя 1 — Подготовка":"Woche 1 — Vorbereitung","Эссе":"Essays","Стратегия поступления":"Bewerbungsstrategie","Собеседования":"Interviews","Резюме & CV":"Lebenslauf & CV","Неделя 2 — Погружение":"Woche 2 — Eintauchen","Экскурсии по вузам":"Universitätsführungen","Нетворкинг":"Networking","Поездка в Нью-Йорк":"Reise nach New York","Понимание цели":"Klare Ziele","Сильное портфолио":"Ein starkes Portfolio","Контакты и опыт":"Kontakte und Erfahrung","Безопасность":"Sicherheit","Топ-преподаватели":"Erstklassige Lehrkräfte","Контроль результата":"Fortschrittskontrolle",
  "Массачусетский технологический институт":"Massachusetts Institute of Technology","Гарвард":"Harvard","Бостон Колледж":"Boston College","Бостонский университет":"Boston University","Северо-Восточный университет":"Northeastern University","Колумбийский университет":"Columbia University","Университеты в New Heaven":"Universitäten in New Haven","Летняя Школа":"Sommerschule","Курсы в Гарварде":"Kurse in Harvard","Помощь в поступлении":"Bewerbungsunterstützung","Лекции":"Unterricht","Проживание в двухместных номерах":"Unterkunft in Doppelzimmern","Трансфер":"Transfers","Размещение":"Unterkunft","Завтрак":"Frühstück","Проживание и сопровождение":"Unterkunft und Betreuung","Посещение университетов лиги плюща. Встречи c сотрудниками и студентами":"Ivy-League-Besuche und Treffen mit Mitarbeitern und Studierenden","Профессора":"Professoren","Администрация":"Universitätsmitarbeiter","Студенты":"Studierende",
  "Приглашение в летнюю школу":"Einladung zur Sommerschule","Участники получают приглашение в летнюю школу, которое используется при оформлении визы B1, предназначенной для деловых поездок.":"Teilnehmende erhalten eine Einladung zur Sommerschule, die bei der Beantragung eines B1-Visums verwendet werden kann.","Наша команда":"Unser Team","Более двух лет опыта организации летних школ и поездок по кампусам университетов.":"Mehr als zwei Jahre Erfahrung mit Sommerschulen und Campusreisen.","🇰🇬 Кыргызстан":"🇰🇬 Kirgisistan","🇰🇿 Казахстан":"🇰🇿 Kasachstan","🇺🇿 Узбекистан":"🇺🇿 Usbekistan","🇷🇺 Россия":"🇷🇺 Russland",
  "Запишитесь на летнюю программу:":"Für das Sommerprogramm anmelden:","Получите PDF-программу и консультацию по датам":"Programm-PDF und Beratung zu den Terminen erhalten","Ваше имя":"Ihr Name","Возраст ребенка":"Alter des Kindes","Страна":"Land","Способ связи":"Bevorzugter Kontaktweg","Отправить":"Senden","Заполните поле: Ваше имя":"Bitte Namen eingeben","Заполните поле: Email":"Bitte E-Mail-Adresse eingeben","Введите корректный Email":"Bitte gültige E-Mail-Adresse eingeben","Заполните поле: Способ связи":"Bitte Kontaktweg auswählen","Связаться с нами":"Kontakt","Подробнее":"Mehr erfahren","Первая неделя":"Erste Woche","входит в оба формата":"in beiden Formaten enthalten","Вторая неделя":"Zweite Woche","дополнительно к базовому пакету":"zusätzlich zum Basispaket","Почему родители выбирают БостонГрад":"Warum Eltern BostonGrad wählen","Понятная стратегия":"Eine klare Strategie","Безопасный формат":"Ein sicheres Format","Реальный опыт Бостона":"Boston wirklich erleben","Следующие шаги":"Klare nächste Schritte","Недельная программа":"Einwöchiges Programm","Погружение в университеты":"Universitäten hautnah erleben","Двухнедельная программа":"Zweiwöchiges Programm","Включает неделю обучения":"Enthält eine Unterrichtswoche","от":"ab","Частые вопросы родителей":"Häufige Fragen","Получить программу":"Programm erhalten"
};
const de: LocaleBundle={code:"de",htmlLang:"de",label:"Deutsch",flag:"🇩🇪",messages}; export default de;
