import type { LocaleBundle } from "../types";

const messages: Record<string, string> = {
  "Домой":"Inicio","Главная":"Inicio","Главная страница":"Página de inicio","Проживание":"Alojamiento","Программа":"Programa","Навигация":"Navegación","Университеты":"Universidades","Истории участников":"Historias de estudiantes","Услуги":"Servicios","Как проходит обучение":"Cómo funciona el programa","Консультация":"Consulta","Оставить заявку":"Solicitar información","Летняя школа":"Escuela de verano","Политика конфиденциальности":"Política de privacidad","Страницы пока не существует":"Esta página aún no existe","Что входит в программу":"Qué incluye el programa",
  "Подготовка к поступлению в колледжи и университеты США":"Preparación para ingresar en universidades de EE. UU.","Курсы в Бостоне, поездка по кампусам университетов лиги плюща":"Cursos en Boston y visitas a campus de la Ivy League","Программа на 2 недели":"Programa de dos semanas","Почему выбирают нас":"Por qué nos eligen las familias","Мы не продаем тур. Мы готовим к поступлению.":"No vendemos un tour. Preparamos para la admisión.","Стоимость программы":"Precio del programa","От $3,000 за 2 недели":"Desde $3,000 por dos semanas","Финальная стоимость зависит от состава программы":"El precio final depende del programa elegido","Узнать точную стоимость":"Obtener un presupuesto exacto",
  "Обучение в кампусе Гарварда":"Clases en el campus de Harvard","Посещение университетов Бостона, Нью-Хевена и Нью-Йорка":"Visitas a universidades de Boston, New Haven y Nueva York","Полное сопровождение, проживание, трансфер и поддержка":"Supervisión, alojamiento, traslados y apoyo completos","Личное знакомство с сотрудниками университетов и студентами":"Encuentros personales con personal y estudiantes universitarios","Неделя 1 — Подготовка":"Semana 1 — Preparación","Эссе":"Ensayos","Стратегия поступления":"Estrategia de admisión","Собеседования":"Entrevistas","Резюме & CV":"Currículum y CV","Неделя 2 — Погружение":"Semana 2 — Inmersión","Экскурсии по вузам":"Visitas universitarias","Нетворкинг":"Networking","Поездка в Нью-Йорк":"Viaje a Nueva York","Понимание цели":"Objetivos claros","Сильное портфолио":"Un portafolio sólido","Контакты и опыт":"Contactos y experiencia","Безопасность":"Seguridad","Топ-преподаватели":"Profesores excelentes","Контроль результата":"Seguimiento del progreso",
  "Массачусетский технологический институт":"Instituto Tecnológico de Massachusetts","Гарвард":"Harvard","Бостон Колледж":"Boston College","Бостонский университет":"Boston University","Северо-Восточный университет":"Northeastern University","Колумбийский университет":"Universidad de Columbia","Университеты в New Heaven":"Universidades de New Haven","Летняя Школа":"Escuela de verano","Курсы в Гарварде":"Cursos en Harvard","Помощь в поступлении":"Apoyo para la admisión","Лекции":"Clases","Проживание в двухместных номерах":"Alojamiento en habitaciones dobles","Трансфер":"Traslados","Размещение":"Alojamiento","Завтрак":"Desayuno","Проживание и сопровождение":"Alojamiento y supervisión","Посещение университетов лиги плюща. Встречи c сотрудниками и студентами":"Visitas a universidades de la Ivy League y encuentros con personal y estudiantes","Профессора":"Profesores","Администрация":"Personal universitario","Студенты":"Estudiantes",
  "Приглашение в летнюю школу":"Invitación a la escuela de verano","Участники получают приглашение в летнюю школу, которое используется при оформлении визы B1, предназначенной для деловых поездок.":"Los participantes reciben una invitación a la escuela de verano que puede utilizarse al solicitar una visa B1.","Наша команда":"Nuestro equipo","Более двух лет опыта организации летних школ и поездок по кампусам университетов.":"Más de dos años organizando escuelas de verano y visitas universitarias.","🇰🇬 Кыргызстан":"🇰🇬 Kirguistán","🇰🇿 Казахстан":"🇰🇿 Kazajistán","🇺🇿 Узбекистан":"🇺🇿 Uzbekistán","🇷🇺 Россия":"🇷🇺 Rusia",
  "Запишитесь на летнюю программу:":"Solicita una plaza en el programa de verano:","Получите PDF-программу и консультацию по датам":"Recibe el programa en PDF y una consulta sobre las fechas","Ваше имя":"Tu nombre","Возраст ребенка":"Edad del estudiante","Страна":"País","Способ связи":"Medio de contacto preferido","Отправить":"Enviar","Заполните поле: Ваше имя":"Introduce tu nombre","Заполните поле: Email":"Introduce tu email","Введите корректный Email":"Introduce un email válido","Заполните поле: Способ связи":"Selecciona un medio de contacto","Связаться с нами":"Contáctanos","Подробнее":"Más información","Первая неделя":"Primera semana","входит в оба формата":"incluida en ambos formatos","Вторая неделя":"Segunda semana","дополнительно к базовому пакету":"adicional al paquete básico","Почему родители выбирают БостонГрад":"Por qué los padres eligen BostonGrad","Понятная стратегия":"Una estrategia clara","Безопасный формат":"Un formato seguro","Реальный опыт Бостона":"Una experiencia real en Boston","Следующие шаги":"Próximos pasos claros","Недельная программа":"Programa de una semana","Погружение в университеты":"Inmersión universitaria","Двухнедельная программа":"Programa de dos semanas","Включает неделю обучения":"Incluye una semana de clases","от":"desde","Частые вопросы родителей":"Preguntas frecuentes","Получить программу":"Recibir el programa"
};
const es: LocaleBundle={code:"es",htmlLang:"es",label:"Español",flag:"🇪🇸",messages}; export default es;
