import type { LocaleBundle } from "../types";
const messages: Record<string,string>={
  "Домой":"Accueil","Главная":"Accueil","Главная страница":"Page d'accueil","Проживание":"Hébergement","Программа":"Programme","Навигация":"Navigation","Университеты":"Universités","Истории участников":"Témoignages","Услуги":"Services","Как проходит обучение":"Déroulement du programme","Консультация":"Consultation","Оставить заявку":"Faire une demande","Летняя школа":"École d'été","Политика конфиденциальности":"Politique de confidentialité","Страницы пока не существует":"Cette page n'existe pas encore","Что входит в программу":"Ce que comprend le programme",
  "Подготовка к поступлению в колледжи и университеты США":"Préparation à l'admission dans les universités américaines","Курсы в Бостоне, поездка по кампусам университетов лиги плюща":"Cours à Boston et visites de campus de l'Ivy League","Программа на 2 недели":"Programme de deux semaines","Почему выбирают нас":"Pourquoi les familles nous choisissent","Мы не продаем тур. Мы готовим к поступлению.":"Ce n'est pas un circuit touristique. C'est une préparation à l'admission.","Стоимость программы":"Prix du programme","От $3,000 за 2 недели":"À partir de 3 000 $ pour deux semaines","Финальная стоимость зависит от состава программы":"Le prix final dépend du programme choisi","Узнать точную стоимость":"Obtenir un tarif précis",
  "Обучение в кампусе Гарварда":"Cours sur le campus de Harvard","Посещение университетов Бостона, Нью-Хевена и Нью-Йорка":"Visites d'universités à Boston, New Haven et New York","Полное сопровождение, проживание, трансфер и поддержка":"Encadrement, hébergement, transferts et assistance complets","Личное знакомство с сотрудниками университетов и студентами":"Rencontres avec le personnel et les étudiants des universités","Неделя 1 — Подготовка":"Semaine 1 — Préparation","Эссе":"Essais","Стратегия поступления":"Stratégie d'admission","Собеседования":"Entretiens","Резюме & CV":"Résumé et CV","Неделя 2 — Погружение":"Semaine 2 — Immersion","Экскурсии по вузам":"Visites d'universités","Нетворкинг":"Réseautage","Поездка в Нью-Йорк":"Voyage à New York","Понимание цели":"Objectifs clairs","Сильное портфолио":"Un dossier solide","Контакты и опыт":"Contacts et expérience","Безопасность":"Sécurité","Топ-преподаватели":"Excellents enseignants","Контроль результата":"Suivi des progrès",
  "Массачусетский технологический институт":"Massachusetts Institute of Technology","Гарвард":"Harvard","Бостон Колледж":"Boston College","Бостонский университет":"Boston University","Северо-Восточный университет":"Northeastern University","Колумбийский университет":"Université Columbia","Университеты в New Heaven":"Universités de New Haven","Летняя Школа":"École d'été","Курсы в Гарварде":"Cours à Harvard","Помощь в поступлении":"Aide à l'admission","Лекции":"Cours","Проживание в двухместных номерах":"Hébergement en chambres doubles","Трансфер":"Transferts","Размещение":"Hébergement","Завтрак":"Petit-déjeuner","Проживание и сопровождение":"Hébergement et encadrement","Посещение университетов лиги плюща. Встречи c сотрудниками и студентами":"Visites de l'Ivy League et rencontres avec le personnel et les étudiants","Профессора":"Professeurs","Администрация":"Personnel universitaire","Студенты":"Étudiants",
  "Приглашение в летнюю школу":"Invitation à l'école d'été","Участники получают приглашение в летнюю школу, которое используется при оформлении визы B1, предназначенной для деловых поездок.":"Les participants reçoivent une invitation à l'école d'été utilisable pour une demande de visa B1.","Наша команда":"Notre équipe","Более двух лет опыта организации летних школ и поездок по кампусам университетов.":"Plus de deux ans d'expérience dans l'organisation d'écoles d'été et de visites de campus.","🇰🇬 Кыргызстан":"🇰🇬 Kirghizistan","🇰🇿 Казахстан":"🇰🇿 Kazakhstan","🇺🇿 Узбекистан":"🇺🇿 Ouzbékistan","🇷🇺 Россия":"🇷🇺 Russie",
  "Запишитесь на летнюю программу:":"Inscrivez-vous au programme d'été :","Получите PDF-программу и консультацию по датам":"Recevez le programme en PDF et des conseils sur les dates","Ваше имя":"Votre nom","Возраст ребенка":"Âge de l'élève","Страна":"Pays","Способ связи":"Moyen de contact préféré","Отправить":"Envoyer","Заполните поле: Ваше имя":"Saisissez votre nom","Заполните поле: Email":"Saisissez votre e-mail","Введите корректный Email":"Saisissez une adresse e-mail valide","Заполните поле: Способ связи":"Choisissez un moyen de contact","Связаться с нами":"Nous contacter","Подробнее":"En savoir plus","Первая неделя":"Première semaine","входит в оба формата":"incluse dans les deux formules","Вторая неделя":"Deuxième semaine","дополнительно к базовому пакету":"en plus de la formule de base","Почему родители выбирают БостонГрад":"Pourquoi les parents choisissent BostonGrad","Понятная стратегия":"Une stratégie claire","Безопасный формат":"Une formule sûre","Реальный опыт Бостона":"Une vraie expérience de Boston","Следующие шаги":"Des étapes suivantes claires","Недельная программа":"Programme d'une semaine","Погружение в университеты":"Immersion universitaire","Двухнедельная программа":"Programme de deux semaines","Включает неделю обучения":"Comprend une semaine de cours","от":"à partir de","Частые вопросы родителей":"Questions fréquentes","Получить программу":"Recevoir le programme"
};
const fr: LocaleBundle={code:"fr",htmlLang:"fr",label:"Français",flag:"🇫🇷",messages}; export default fr;
