import type { LocaleBundle } from "../types";
const messages: Record<string,string>={
  "Домой":"Início","Главная":"Início","Главная страница":"Página inicial","Проживание":"Alojamento","Программа":"Programa","Навигация":"Navegação","Университеты":"Universidades","Истории участников":"Histórias de alunos","Услуги":"Serviços","Как проходит обучение":"Como funciona o programa","Консультация":"Consulta","Оставить заявку":"Candidatar-se","Летняя школа":"Escola de verão","Политика конфиденциальности":"Política de privacidade","Страницы пока не существует":"Esta página ainda não existe","Что входит в программу":"O que o programa inclui",
  "Подготовка к поступлению в колледжи и университеты США":"Preparação para admissão em faculdades e universidades dos EUA","Курсы в Бостоне, поездка по кампусам университетов лиги плюща":"Cursos em Boston e visitas a campi da Ivy League","Программа на 2 недели":"Programa de duas semanas","Почему выбирают нас":"Por que as famílias nos escolhem","Мы не продаем тур. Мы готовим к поступлению.":"Não vendemos um passeio. Preparamos para a admissão.","Стоимость программы":"Preço do programa","От $3,000 за 2 недели":"A partir de US$ 3.000 por duas semanas","Финальная стоимость зависит от состава программы":"O preço final depende do programa escolhido","Узнать точную стоимость":"Obter um orçamento exato",
  "Обучение в кампусе Гарварда":"Aulas no campus de Harvard","Посещение университетов Бостона, Нью-Хевена и Нью-Йорка":"Visitas a universidades em Boston, New Haven e Nova York","Полное сопровождение, проживание, трансфер и поддержка":"Supervisão, alojamento, traslados e apoio completos","Личное знакомство с сотрудниками университетов и студентами":"Encontros com funcionários e estudantes das universidades","Неделя 1 — Подготовка":"Semana 1 — Preparação","Эссе":"Redações","Стратегия поступления":"Estratégia de admissão","Собеседования":"Entrevistas","Резюме & CV":"Currículo e CV","Неделя 2 — Погружение":"Semana 2 — Imersão","Экскурсии по вузам":"Visitas às universidades","Нетворкинг":"Networking","Поездка в Нью-Йорк":"Viagem a Nova York","Понимание цели":"Objetivos claros","Сильное портфолио":"Um portfólio forte","Контакты и опыт":"Contatos e experiência","Безопасность":"Segurança","Топ-преподаватели":"Excelentes professores","Контроль результата":"Acompanhamento do progresso",
  "Массачусетский технологический институт":"Instituto de Tecnologia de Massachusetts","Гарвард":"Harvard","Бостон Колледж":"Boston College","Бостонский университет":"Boston University","Северо-Восточный университет":"Northeastern University","Колумбийский университет":"Universidade Columbia","Университеты в New Heaven":"Universidades em New Haven","Летняя Школа":"Escola de verão","Курсы в Гарварде":"Cursos em Harvard","Помощь в поступлении":"Apoio à admissão","Лекции":"Aulas","Проживание в двухместных номерах":"Alojamento em quartos duplos","Трансфер":"Traslados","Размещение":"Alojamento","Завтрак":"Café da manhã","Проживание и сопровождение":"Alojamento e supervisão","Посещение университетов лиги плюща. Встречи c сотрудниками и студентами":"Visitas à Ivy League e encontros com funcionários e alunos","Профессора":"Professores","Администрация":"Funcionários universitários","Студенты":"Alunos",
  "Приглашение в летнюю школу":"Convite para a escola de verão","Участники получают приглашение в летнюю школу, которое используется при оформлении визы B1, предназначенной для деловых поездок.":"Os participantes recebem um convite para a escola de verão que pode ser usado no pedido do visto B1.","Наша команда":"Nossa equipe","Более двух лет опыта организации летних школ и поездок по кампусам университетов.":"Mais de dois anos organizando escolas de verão e visitas universitárias.","🇰🇬 Кыргызстан":"🇰🇬 Quirguistão","🇰🇿 Казахстан":"🇰🇿 Cazaquistão","🇺🇿 Узбекистан":"🇺🇿 Uzbequistão","🇷🇺 Россия":"🇷🇺 Rússia",
  "Запишитесь на летнюю программу:":"Inscreva-se no programa de verão:","Получите PDF-программу и консультацию по датам":"Receba o programa em PDF e uma consulta sobre datas","Ваше имя":"Seu nome","Возраст ребенка":"Idade do aluno","Страна":"País","Способ связи":"Forma de contato preferida","Отправить":"Enviar","Заполните поле: Ваше имя":"Digite seu nome","Заполните поле: Email":"Digite seu email","Введите корректный Email":"Digite um email válido","Заполните поле: Способ связи":"Escolha uma forma de contato","Связаться с нами":"Fale conosco","Подробнее":"Saiba mais","Первая неделя":"Primeira semana","входит в оба формата":"incluída nos dois formatos","Вторая неделя":"Segunda semana","дополнительно к базовому пакету":"adicional ao pacote básico","Почему родители выбирают БостонГрад":"Por que os pais escolhem a BostonGrad","Понятная стратегия":"Uma estratégia clara","Безопасный формат":"Um formato seguro","Реальный опыт Бостона":"Uma experiência real em Boston","Следующие шаги":"Próximos passos claros","Недельная программа":"Programa de uma semana","Погружение в университеты":"Imersão universitária","Двухнедельная программа":"Programa de duas semanas","Включает неделю обучения":"Inclui uma semana de aulas","от":"a partir de","Частые вопросы родителей":"Perguntas frequentes","Получить программу":"Receber o programa"
};
const pt: LocaleBundle={code:"pt",htmlLang:"pt",label:"Português",flag:"🇵🇹",messages}; export default pt;
